# =================================
# Eureka Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: albinxavier/eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: NodePort
---
# =================================
# Product Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: albinxavier/productapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: EUREKA_URL
              value: http://eureka:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 7000
      targetPort: 7000
  type: NodePort
---
# =================================
# Order Service
# =================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: albinxavier/orderapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: EUREKA_URL
              value: http://eureka:8761/eureka
            - name: PRODUCT_URL
              value: http://product-service:7000/products
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
